### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by Jacker132** [Schira4396/VcenterKiller#10]
报错：
![image](https://github.com/Schira4396/VcenterKiller/assets/38522348/33221985-26bc-49e9-aece-4c8768828750)
![image](https://github.com/Schira4396/VcenterKiller/assets/38522348/2b1009c9-6de4-4349-a752-c2f3be351c61)

**Comment by Schira4396** [comment]
> 报错： ![image](https://user-images.githubusercontent.com/38522348/273776504-33221985-26bc-49e9-aece-4c8768828750.png) ![image](https://user-images.githubusercontent.com/38522348/273776553-2b1009c9-6de4-4349-a752-c2f3be351c61.png)

我注意到这个问题了，看看先

**Comment by Schira4396** [comment]
可以先用1.3.6

**Comment by Schira4396** [comment]
> 报错： ![image](https://user-images.githubusercontent.com/38522348/273776504-33221985-26bc-49e9-aece-4c8768828750.png) ![image](https://user-images.githubusercontent.com/38522348/273776553-2b1009c9-6de4-4349-a752-c2f3be351c61.png)

请使用go 1.18
