### ISSUE TITLE
代理模式支持socks吗，怎么用代理呢

### ISSUE THREAD

**Issue by IR-create** [Schira4396/VcenterKiller#11]

**Comment by Schira4396** [comment]
> _No description provided._

支持http和socks，参数我也忘了，源码编译完了-h好像有

**Comment by Schira4396** [comment]
使用-proxy参数
![image](https://github.com/Schira4396/VcenterKiller/assets/57404930/a73f957c-6037-487f-aaaa-5c755756a891)
