### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by NSW111** [Schira4396/VcenterKiller#12]
go: downloading github.com/go-resty/resty/v2 v2.7.0
src/log4jcenter/log4j.go:12:2: zip: not a valid zip file
资源已经不存在了，本人对编程一窍不通，导致没办法解决。

**Comment by Schira4396** [comment]
> go: downloading github.com/go-resty/resty/v2 v2.7.0 src/log4jcenter/log4j.go:12:2: zip: not a valid zip file 资源已经不存在了，本人对编程一窍不通，导致没办法解决。

go版本不能太新，用1.18，我晚点打包一下新的上传吧

**Comment by NSW111** [comment]
go版本是1.18，是显示没有资源

**Comment by Schira4396** [comment]
> go版本是1.18，是显示没有资源

刚看了一下是依赖库的问题，在项目目录下执行
`go get -u ./...`
更新依赖后再go build就没问题了铁汁
