### ISSUE TITLE
log4shell Echo support ? Example Tomcat or Spring ......

### ISSUE THREAD

**Issue by 1n7erface** [Schira4396/VcenterKiller#2]
The target has some restrictions on outgoing and needs to be echoed. Only ReverseShell is not enough.

**Comment by Schira4396** [comment]
> The target has some restrictions on outgoing and needs to be echoed. Only ReverseShell is not enough.

不支持，目前只有通过远程加载恶意类来反弹shell哈，好像log4j没有啥回显的利用方式吧。。。还有不出网是怎么个不出网，不出公网还是怎么的

**Comment by Schira4396** [comment]
> The target has some restrictions on outgoing and needs to be echoed. Only ReverseShell is not enough.
还有就是反弹shell这个操作完全是根据你jndi服务指定的类是哪种，我只是在这里把它叫做反弹shell^^

**Comment by 1n7erface** [comment]
如果我使用log4带回显链将数据带出，我希望你能将返回包进行输出或打印，而不是控制台反馈给我请检查。

**Comment by Schira4396** [comment]
> 如果我使用log4带回显链将数据带出，我希望你能将返回包进行输出或打印，而不是控制台反馈给我请检查。

我知道，但是我找了找好像log4j没有比较通用的回显利用链

**Comment by Schira4396** [comment]
> 如果我使用log4带回显链将数据带出，我希望你能将返回包进行输出或打印，而不是控制台反馈给我请检查。
额这波我的 ，刚确认了用tomcatecho的方式可以获得输出，谢谢师傅提醒哈
