### ISSUE TITLE
too many colons in address？

### ISSUE THREAD

**Issue by Artio-Li** [Schira4396/VcenterKiller#3]
使用命令： ./vckiller_linux_amd64 -u http://192.168.248.1:8983 -m log4center -t scan

[*] url: http://192.168.248.1:8983
[*] 启动端口监听.
dial tcp: address 192.168.248.1:8983:443: too many colons in address
[*] your local IP: 

报错too many colons in address，自动加了一个443端口？

**Comment by Schira4396** [comment]
> 使用命令： ./vckiller_linux_amd64 -u http://192.168.248.1:8983 -m log4center -t scan
> 
> [_] url: http://192.168.248.1:8983 [_] 启动端口监听. dial tcp: address 192.168.248.1:8983:443: too many colons in address [*] your local IP:
> 
> 报错too many colons in address，自动加了一个443端口？

等我修改一下，我没考虑到有的应用会更改端口这个问题，443是我写死了的

**Comment by Schira4396** [comment]
> 使用命令： ./vckiller_linux_amd64 -u http://192.168.248.1:8983 -m log4center -t scan
> 
> [_] url: http://192.168.248.1:8983 [_] 启动端口监听. dial tcp: address 192.168.248.1:8983:443: too many colons in address [*] your local IP:
> 
> 报错too many colons in address，自动加了一个443端口？

而且scan这个功能里头有这么一步：根据目标IP判断自己主机的出口IP，来触发rmi远程调用，实现这个功能就得先用socket去连接，这个socket是写死了连443端口的

**Comment by Schira4396** [comment]
> 使用命令： ./vckiller_linux_amd64 -u http://192.168.248.1:8983 -m log4center -t scan
> 
> [_] url: http://192.168.248.1:8983 [_] 启动端口监听. dial tcp: address 192.168.248.1:8983:443: too many colons in address [*] your local IP:
> 
> 报错too many colons in address，自动加了一个443端口？

已经修复了哈

**Comment by Artio-Li** [comment]
好的
