### ISSUE TITLE
Centos7  报错

### ISSUE THREAD

**Issue by WhiteHSBG** [Schira4396/VcenterKiller#6]
[root@VM-8-2-centos ~]# ./vckiller_linux_amd64
./vckiller_linux_amd64: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./vckiller_linux_amd64)
./vckiller_linux_amd64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./vckiller_linux_amd64)

[root@VM-8-2-centos ~]# uname -a
Linux VM-8-2-centos 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
是否能编译多几个版本的release，比如mac版

**Comment by Schira4396** [comment]
> [root@VM-8-2-centos ~]# ./vckiller_linux_amd64 ./vckiller_linux_amd64: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./vckiller_linux_amd64) ./vckiller_linux_amd64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./vckiller_linux_amd64)
> 
> [root@VM-8-2-centos ~]# uname -a Linux VM-8-2-centos 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux 是否能编译多几个版本的release，比如mac版

我试试哈，mac的我没这个环境

**Comment by Schira4396** [comment]
> 

跨平台编译可能会有问题

**Comment by Schira4396** [comment]
> [root@VM-8-2-centos ~]# ./vckiller_linux_amd64 ./vckiller_linux_amd64: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./vckiller_linux_amd64) ./vckiller_linux_amd64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./vckiller_linux_amd64)
> 
> [root@VM-8-2-centos ~]# uname -a Linux VM-8-2-centos 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux 是否能编译多几个版本的release，比如mac版

我刚试过了，纯净centos8编译

> [root@VM-8-2-centos ~]# ./vckiller_linux_amd64 ./vckiller_linux_amd64: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./vckiller_linux_amd64) ./vckiller_linux_amd64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./vckiller_linux_amd64)
> 
> [root@VM-8-2-centos ~]# uname -a Linux VM-8-2-centos 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux 是否能编译多几个版本的release，比如mac版

刚确认了是没有关cgo编译导致的，现在修复了，然后mac的也有了哈师傅
