### ISSUE TITLE
go 1.20 打包出错

### ISSUE THREAD

**Issue by Ryze-T** [Schira4396/VcenterKiller#7]
![image](https://user-images.githubusercontent.com/76553352/236748817-68cbe252-8b8b-4935-99da-f849d42401e7.png)

**Comment by Schira4396** [comment]
> ![image](https://user-images.githubusercontent.com/76553352/236748817-68cbe252-8b8b-4935-99da-f849d42401e7.png)

试试换低一点版本的呢，我之前用的是1.18
