### ISSUE TITLE
添加代理选项

### ISSUE THREAD

**Issue by No-Github** [Schira4396/VcenterKiller#9]
我看它 imroc/req 这个库的请求不能被 proxychains 代走,挺麻烦的

加个 SetProxyURL 就行
```
	client := req.C()
	client.SetProxyURL("http://x.x.x.x:8080")
```
辛苦一下,加个配置吧

**Comment by Schira4396** [comment]
> 我看它 imroc/req 这个库的请求不能被 proxychains 代走,挺麻烦的
> 
> 加个 SetProxyURL 就行
> 
> ```
> 	client := req.C()
> 	client.SetProxyURL("http://x.x.x.x:8080")
> ```
> 
> 辛苦一下,加个配置吧

proxychains改代理我倒是没试过，不过我记得在Windows上用proxifer都能改的来着，至于程序本身的代理我这两天加一个，谢谢你的建议。

**Comment by Schira4396** [comment]
> 我看它 imroc/req 这个库的请求不能被 proxychains 代走,挺麻烦的
> 
> 加个 SetProxyURL 就行
> 
> ```
> 	client := req.C()
> 	client.SetProxyURL("http://x.x.x.x:8080")
> ```
> 
> 辛苦一下,加个配置吧

已经添加代理
